# Language-helper middleware for Express web server.

# Copyright (C) 2016-2017 Volebo <dev@volebo.net>
# Copyright (C) 2016-2017 Maksim Koryukov <maxkoryukov@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the MIT License, attached to this software package.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# You should have received a copy of the MIT License along with this
# program. If not, see <https://opensource.org/licenses/MIT>.

sudo: false

language: node_js

node_js:
  - 4
  - 6

# env:
#  global:
#    - NODE_ENV=dev

# matrix:
#  allow_failures:
#    - node_js: 4

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

install:
  - npm install -g npm
  - npm install -g eslint
  # - npm install -g gulp
  - npm install
  - npm install -g codecov
  - npm install -g bithound

  # peer dependency:
  - npm install express

script:
# - gulp build
  - npm run lint
  - npm test
  - npm run coverage
  - bithound check git@github.com:$TRAVIS_REPO_SLUG.git

after_success:
  - codecov

deploy:
  provider: npm
  api_key:
    secure: Ivf1sGIwm+yZHgbT013DLfdk/FST97cyWgOb2OwKb7jLfS57RCBb5gOUrAbDd9df84xscnjidGDa+sLxagnn1RqG35lgXjUizgTULLgRr2lY3Orr32vjHarOwBYkOtx7IJWXLge+wuoZr1QonXNNUB+Fl3f+U7aYdqE/DktjCagMmFHSXPKojc8+N9dNfu4ZquniGEtOxv15BfjP08XIjGOfZzOnWp4y42kYZz+93Fh5AzYAYQCkRcVSdPtjeIeFEVChsfuj5jSKygo1w1zKfVuQZ4orqFSAiWJ8HGW0Jrvj5dYfOD5OQ3srnMmax5gt7suj/ZZ9HRZT7+rv4QNW3w0KFQ/L9R85rAB8IcTmaZU8A94dJE8L3dToPgMqnXL0div1NHuHNlbpNbrFcleX0wWSh3aCcuGWrZM+Q+uyZCs684eOEaY3VfTTrcv4tY3y5YXGE4lMCxX2mc1J9mRy0GwNUKR2bk/cuDZllyARc7as/SB4n7bKsijBy58N/I9sqMCPMQrNk8M9/g/PYNRtsSWI9G+zQr5NI6anvl88h7FF0MDTFkb6Cd5BOetLafjNN4VVRMoUEF161RxLkUpjdiM2uU15XzYqqD5QYOEvOfM4uwkfdRZiPCPxYtH12BdnfdgWVHjqyQG3kgSTlfowYATfA3UkdD/JY1U5F3aWnCI=
  email:
    secure: TXbFHnByBfD5AT3tRtyaU967o8U7EFdhEP+UVh43D1hntRMB2Xm6gJ324XRp8QzC6SKaYA0oTxR67sU2bSXQRH2cE9+S+0c/Dn+NOD2IuTeZsyqcVq+gHQx7VRyi/pHr36nVi0deC9CU07YDfTaayDU8dvEaVlcjM68XUt2EgsnlFp8QnAeDvXrBgnsT9d+UqIl8smqYYuCUZqRpZypjDSSSQI0p41L73bHBTSfahz2R63kODKIHNrNSINm+WMJyzxa1Tp90XXtBpCBIfxzWIhOBrR8g+naA5iHoWR7wRdO8fQafyPLwFa8AtKXG7n4EHRBe0I4877aatbT8ImbnS5eOqzyGosRdxHOGppcmP9bYjxcy0JORrXVZTB7j4KSsKg7QDpcKjVO/0OqTvbC3JLp9eIthP1Y8e433zrpsr/AJM2SL0IljtYNwoWvv8tfFuMZIPzIcy2ttrh8gLH/JFHXMry6YktY0uPttUd+fPyPbHQXKGsHUyj2xknL/6VWM+ZTEZMYJg/xd4XcDhzqX4W8OdgSjl5ComS4c7o9g6YTnh91WivIkzbTEOk8AqgBXAvlqm2wy29vY1KkEqHwzbk5cK0Y9IdYFDnSpDLM6vnObcSZRQtEaIn0t9g/LMoFt6BGG8ekFFctHTw1/LvNZBNub4qs+PMeZ/hI5PZKRbd0=
  on:
    tags: true
    node_js: 6
    repo: volebo/express-mw-lang
