# Language-helper middleware for Express web server.

# Copyright (C) 2016-2017 Volebo <dev@volebo.net>
# Copyright (C) 2016-2017 Maksim Koryukov <maxkoryukov@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the MIT License, attached to this software package.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# You should have received a copy of the MIT License along with this
# program. If not, see <https://opensource.org/licenses/MIT>.

sudo: false

language: node_js

node_js:
#  - 4
  - 6

# env:
#  global:
#    - NODE_ENV=dev

# matrix:
#  allow_failures:
#    - node_js: 4

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

install:
  - npm install -g npm
  - npm install -g eslint
  # - npm install -g gulp
  - npm install
  - npm install -g codecov
  - npm install -g bithound

  # peer dependency:
  - npm install express

script:
# - gulp build
  - npm run lint
  - npm test
  - npm run coverage
  - codecov
  - bithound check git@github.com:$TRAVIS_REPO_SLUG.git

deploy:
  provider: npm
  api_key:
    secure: "pP/UsyDJalIt+Pn0UvQ2UnawlzpExNWdRBU1ITrlJ67itjQxZ7Mo25PStcbW8SHGOTezcxDcfF3KIzi6RDWwiZCbJjDL8r0dire2IJ0JSrvBAJkAmJ29VpIvDL6Ec2isEL4E2QYPup/wcljOtQ1tBuRz7pUgJNls3xMGE94J6gT5KEah7bVLFLI5bkYRA73ot+l/gq1VH1lndMbQc7cS7k0TiwYxgRhOiYFUde9qzWw6Fmbp7u6IfkY1Nf3X0WE5bH9XfcRUWsDcvb1By0hKDAN+n2mioXA8KsOdAhk35+rnF1gTp4vXkGxM3MiyL1/x9S8YMUlEUdtv2Z9He1KNroValqorsJqSd1T4RtyDd5rH5ehhH7er1douHcFEBKtJLmnBNlvc9tEhpDTqV0EoVqyLBYg73xhGUlkIjzgPIDGGsBAFplyTk5OPkOpsJEXXonb41aZ72XenCk1bZMOu/SgnY9JD/2ii3ZdbUeR2dOdZKOOzF0sq4OoMnxEM6GGRTTMenh/Hn3OXudJFeTVs/myh0BLfHl1vfRLJu21njK7TS9E4MMhdGbnyQ9lEBm5t7pTIyYmFVdfWqs8x6eCKTF9rsL2f7jDVFZ1eGU7QldJfbNH/Yo/ycUueTeNdi2txJTZMVSTWYHupKMZYLpPcyEhF3+C7aguRiKxfanI0hKo="
  email:
    secure: "AJ8J5mZKmFgUewSRBcSMOAFxZNQB1uQUZcxNHLCuCWE3uAHLj1D7dXTGVg9haelaxagSzMGacD7Zq/sI4LqJuMiS5nBPNco/QRiMra3GRmkgD6DUogCPBHSgrYcmn5AOMzwRE61IE/JB+eg83HQH5gsQbSUAWbCITvDlprDWLuOe4vGvjNgMJ7Ue1h0eW2dVpMZxkLFR9WlYSMDO4t9ja9zAV0mSeTPLVG2pOfNTxJQCLb2s7I4wWfQA48Ngayk9IwUOdU/oV5hr47jUZo/aPYBjsjRS35lWgaFgjhNVR7cOXzykeGDYvlxnSTcwvNpjVvAnwiiaN0QyR4hotG3JNO3Pf3zB4bJJyumncSX7xsgooRKN6jhuCh8dz/fyYW0CvgvbZ0mK0Yx8BqQ+FBV7ibe57OiK+7+ZsiOYhv3dQf/2RUP8BV72APKNyX6vBN4rhT7HB09bV3fjvH6I1gryuRhRYGu8qjvbvZZj40+s8+jODBvL6V7jMN3VrGmBWnYTxqGaDgynmgYM/0jD0vpwOz7xpT/jCb9p4adCPuVZZ7KiWd6dSTAVTQWxvqAn15fiPUvlyNv/QZefqKSs+yqFTWfdcOURP83MvtLIC/sIWP5MjRgRiB7oNWnr3GMjvqhp3SbWc9x/8Lz/IDn0dBugjUJGwnPd0sLVGgg+iL7GWOg="
  on:
    tags: true
    node_js: 6
    repo: volebo/express-mw-lang

after_deploy:
  # Send notification to Slack:
  - curl -sL https://raw.githubusercontent.com/volebo/dev/master/scripts/im/slack-publish.sh | bash -s -
